### ISSUE TITLE
Handle multiple major ircd versions

### ISSUE THREAD

**Issue by prawnsalad** [irccom/test-servers#5]
Maybe suffixing each folder eg. `charybdis-3.5` `charybdis-4`

**Comment by DanielOaks** [comment]
This is now done for the servers that warrant it, namely: Chary, Insp, Hybrid, and Unreal. If there's any other servers that require the specific versions just note them and I can rename/etc them as we go. For any other requests, give us how specific you think we should be with them (e.g. InspIRCd-2.0, InspIRCd-2.1, InspIRCd-2.2, etc, or just Unreal-3, Unreal-4. given how weird some servers are with bumping major version numbers (irc2 for example), we'll need to be more and less specific).
